### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Abab-bk** [RunnerLord/SaveNode#2]
Sorry to bring up this issus, but I really don't know how to use it, maybe you should write a short description :)
I tried adding savenode node to the scene and then `$savenode.saveData()`, but it didn't work

**Comment by KuroyukiDev** [comment]
@Abab-bk did you enable it in the Plugin Manager settings in the Project settings? also, from what the plugin's code is written like, there isn't any function called:
`saveData()`

but there are the functions called:
`_save_data()`
and
`_load_data()`
on the save node. 

That said, I actually haven't taken a moment to look at what the name of the saving/loading data node is called, but the Plugin's code seems to be auto-creating the node on game load so it doesn't seem to be needing a manual creation of the node. To figure the name of the node in the Scene Tree, I suggest looking at the tree while in Playtesting Mode is Active since it'll have it listed in the Scene Tree during runtime. However if the Plugin isn't enabled in the Project settings, the project wouldn't know it exists. 

Though the LifeCycle Method `_enter_tree()` in the Plugin's `main.gd` file is running the code:
```gdscript
func _enter_tree():
	add_custom_type("SaveNode", "Node", preload("res://addons/save_node/main/save_node.gd"), preload("res://addons/save_node/editor/icons/SaveNode.svg"))
```
and the `_exit_tree()` method is removing the node.

That code above is telling us that the name of the Save Node is `SaveNode` and its of class type `Node`.

When referencing a node/class by name, you need to remember that they are case-sensitive so your code:
`$savenode.saveData()`
would actually need to be:
`$SaveNode._save_data()`

Though I do agree that there's not much info on *how* this Plugin works but a quick read-over of the source code can tell you *what* its doing. The thing I don't get is how to set the values of the SaveNode's exported variables with custom values in the editor if its being auto-created like how the Plugin's `main.gd` script is doing.....

**Comment by Abab-bk** [comment]
ok, thx for your answer.
